info:
  app:
    name: My Application
    version: "1.0.0"
    description: Spring Boot demo
    developer:
      name: Mohamed Sidatt
      email: medsidatt@example.com

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/mpiag_tps
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8090

actuator:
  base-url: http://localhost:8090/actuator
